### ISSUE TITLE
This site shows an older version: https://neat.joeldare.com/

### ISSUE THREAD

**Issue by Polyducks** [codazoda/neatcss#21] opened 2021-02-19 21:52 UTC
The URL shows an older version of the styles where button and .button weren't merged into one rule. I made a fork to clean up the CSS only to find it was already fixed.

-PDX

**Comment by codazoda** [comment] 2021-02-20 12:09
Yeah, I'm sorry about that. The demo site runs on the released version (0.0.4) while the code in the repo is a bit ahead of that release. I suppose I should add that info to a `CONTRIBUTING.txt` or similar.

**Comment by Polyducks** [comment] 2021-02-20 21:29
It might be possible to set up an automatic deployment each time there's a major update. I'm sorry, I'm not knowledgable enough in this realm. 

It's a small project so it's not impractical if you wanted to update by hand if the changes aren't all that often.

**Comment by codazoda** [comment] 2021-03-01 20:22
I'm going to close this issue because having the demo site on the currently released version is by design, at the moment.

**Closed by codazoda** 2021-03-01 20:22 UTC
